### ISSUE TITLE
Jenkins crash where building project that contain files with accents

### ISSUE THREAD

**Issue by GautierDig** [jenkinsci/docker-ssh-agent#132]
### Jenkins and plugins versions report

Jenkins crash with the `Malformed input or input contains unmappable characters: /home/jenkins/agent/workspace/src/wp/wp-content/uploads/2017/11/._MiniatureAirDuDésertMarocainMiniatureInWueste-624x964.jpg8672861676435183506.tmp` when building a project where some files have accents.

I am using the latest jenkins/ssh-agent:jdk11.

### What Operating System are you using (both controller, and any agents involved in the problem)?

The docker image in ubuntu 20.04.3 with the latest jenkins/ssh-agent:jdk11.

### Reproduction steps

Build a project where some files have accents

### Expected Results

it builds

### Actual Results

get error `Malformed input or input contains unmappable characters: /home/jenkins/agent/workspace/src/wp/wp-content/uploads/2017/11/._MiniatureAirDuDésertMarocainMiniatureInWueste-624x964.jpg8672861676435183506.tmp`

**Comment by MarkEWaite** [comment]
I believe that you need to set the locale of the process to a version that supports the character set you are trying to display.  I typically do that by passing the environment variable `LANG=C.UTF-8`.

**Comment by GautierDig** [comment]
Hi @MarkEWaite, how can I pass this environment variable ? I try via the Jenkinsfile:

```
pipeline {
    agent any

    environment {
            LANG = 'C.UTF-8'
    }

    stages {...
```

But it doesn't seem to work, I still have the same error. I use a multibranch pipeline, I also tried with the module https://plugins.jenkins.io/envinject/ but it doesn't seem to work with multibranch pipeline.

**Comment by MarkEWaite** [comment]
I set `LANG=C.UTF-8` on the computers that run my agents and assure that the agent has the locale set correctly when the agent starts.

I don't know if declarative Pipeline sets the environment variables before or after the implicit checkout that precedes all other steps of the PIpeline.  If it does, then you could use [`options { skipDefaultCheckout() }` ](https://www.jenkins.io/doc/book/pipeline/syntax/#available-options) to bypass the implicit checkout and then perform the checkout yourself with `checkout scm`

**Comment by MarkEWaite** [comment]
It could be that `C.UTF-8` is not an available locale on your operating system.  The command `locale -a` will list the allowed values for the `LANG` and `LC_ALL` environment variables.

It could be that `LC_ALL` is set to a different value (like `C`) and that overrides the value of `LANG`.

It could be that the process that is failing does not have the `LANG` environment variable set because it is not set by the Pipeline until after the failing process has started.

It could be that the file system that you are using does not support UTF-8 characters in file names, even if the operating system supports them.

You could create a tar file with interesting file names in it and then use a test Pipeline to download the tar file and then unpack it.  If that succeeds, then the Pipeline is setting the `LANG` variable early enough that `tar` works.  If that fails, then something is causing the setting of the `LANG` variable to be ignored or treated as invalid.

**Comment by MarkEWaite** [comment]
Closing since there has been no response since July 2022 and I'm unable to duplicate the issue
