### ISSUE TITLE
Add Ubuntu base images

### ISSUE THREAD

**Issue by ju2wheels** [jenkinsci/docker-ssh-agent#412]
### What feature do you want to see added?

Add Ubuntu 22.04/24.04 base images in addition to the debian base images for those that may need the Ubuntu base.

### Are you interested in contributing this feature?

Yes, I started it here https://github.com/tvision-insights/docker-ssh-agent/tree/feature/ubuntu_agent  , if its likely to be accepted I just need feedback on the image tagging guidelines so I can then also add the 24.04 config .

**Comment by MarkEWaite** [comment]
Thanks for the request.  The Jenkins platform SIG is not ready to add more operating system variants to the set of agent operating systems.  Each time an operating system is added, it increases the items that need security tracking, need maintenance, and need enhancements.  As one of the maintainers, I'm not willing to add more platforms.  We're actively choosing to reduce supported container platforms across the Jenkins project rather than adding additional operating system variants.

Other maintainers are welcome to share their opinions, especially if they disagree with my opinion.

**Comment by gounthar** [comment]
Thanks, @ju2wheels and @MarkEWaite.

As much as I love having new platforms/images for Jenkins agents, I agree with Mark regarding maintenance and security. What might be the reason someone would need Ubuntu as a base image instead of Debian?

Nice work on the PR, though.

**Comment by ju2wheels** [comment]
> What might be the reason someone would need Ubuntu as a base image instead of Debian?

Whats the reason you have Alpine instead of just Debian... they are not the same. Thanks though.

**Comment by dduportal** [comment]
Hi @ju2wheels , we provide Alpine and sometime Ubi as these distributions have different packages and ecosystems (such as `musl` In Alpine instead of `glibc` usually).

Our question about the need for Ubuntu is because Ubuntu and Debian are package and binary compatible. In the context of a Docker image, it does not make a lot of sense to provide both, while providing Alpine helps people using programs linked with `musl`.

**Comment by gounthar** [comment]
Thanks for giving some more context, @dduportal . 🙏
